---
version: '3.3'
services:
  redis-dev:
    container_name: redis-dev
    image: redis:5.0-rc
  bot-dev:
    build:
      context: ../
      args:
        PROJECT_PATH: github.com/novitoll/novitoll_daemon_bot
    image: bot:0.0.3
    container_name: bot-dev
    environment:
      - REDIS_HOST=redis-dev
      - REDIS_PORT=6379
      - APP_LANG=rus
    env_file:
      - ./.env-green
    ports:
      - "8081:8080"
    links:
      - redis-dev
    depends_on:
      - redis-dev
    volumes:
      - "../:/opt/src/github.com/novitoll/novitoll_daemon_bot"
