---
version: '3.3'
services:
  router:
    build:
      context: ../
      args:
        PROJECT_PATH: github.com/novitoll/novitoll_daemon_bot
        MAKEFILE_TARGET: router
    image: router:0.0.9
    container_name: router
    env_file:
      - ./.env
    ports:
      - "1909:8080"
    volumes:
      - "../:/opt/src/github.com/novitoll/novitoll_daemon_bot"