---
version: '3.3'
services:
  redis:
    container_name: redis
    image: redis:5.0-rc
  bot:
    build:
      context: ../
      args:
        PROJECT_PATH: github.com/novitoll/novitoll_daemon_bot
    image: bot:0.0.3
    container_name: bot
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TELEGRAM_URL=http://telegrammock:8081/%s/%s
      - APP_LANG=en-us
    env_file:
      - ./.env-local
    ports:
      - "8080:8080"
    links:
      - redis
     - telegrammock
    depends_on:
      - redis
    volumes:
      - "../:/opt/src/github.com/novitoll/novitoll_daemon_bot"

